version: "2.2"

services:
  redis:
    image: redis
    command: redis-server
    ports:
      - "${DOCKER_BASE_REDIS_SERVER_PORT:-6379}:6379" #Redis server

  autocampus-icu-backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: AutOCampus-ICU-Backend
    command: python app/autOCampus-icu-backend/manage.py runserver 0.0.0.0:8000 --noreload
    volumes:
      - .:/app
    ports:
      - "${DOCKER_BASE_APP_PORT:-8012}:8000" # Web app
    restart: "always"
    links:
      - redis
    depends_on:
      - redis
    environment:
      # DEBUG is the app. debugging feature
      # SIM is the read-only mode (i.e no write to any database) for testing purposes
      # DEVEL force sqlite usage (==> no Postgres usage)
      # DJANGO_DEBUG as you guessed ;)
      - PYTHONUNBUFFERED=1
      - DJANGO_DEBUG
      - DEBUG
      - SIM
      - DEVEL
      # [apr.22] DJANGO_SECRET_KEY will get regenerated every whole app restart
      - DJANGO_SECRET_KEY=4!+f*30)%_^u(&pbz0#ldt+-p5ez(i@auul%j#7@(bgt-*y)#d
      # MQTT
      - MQTT_SERVER=neocampus.univ-tlse3.fr
      - MQTT_PORT=1883
      - MQTT_TIMEOUT=60
      - MQTT_USER=test
      - MQTT_PASSWD
      # json format for MQTT_TOPICS to subscribe to
      - MQTT_TOPICS={ "1":"TestTopic/devices" }
      # DB backend (unless overriden by DEVEL env var)
      - PGSQL_USER=autocampus-icu
      - PGSQL_PASSWD
      - PGSQL_SERVER=172.17.0.1
      - PGSQL_PORT
      - PGSQL_DATABASE=autocampus-icu
